codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...70"

  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false

ignore:
  - "Mock*.kt"
  - "app/src/main/kotlin/kt/school/starlord/di/.*"
  - "app/src/main/kotlin/kt/school/starlord/entity/.*"
