language: android

before_install:
  - openssl aes-256-cbc -K $encrypted_d9066dcd8080_key -iv $encrypted_d9066dcd8080_iv
    -in keys/keystore.jks.enc -out keys/keystore.jks -d
  - yes | sdkmanager "platforms;android-28"

before_deploy:
  - git config --local user.name "travis"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $github_api_key
  file_glob: true
  file: app/build/outputs/apk/release/*
  on:
    branch: master
