language: android
sudo: required
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - tools

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android/build-cache

before_install:
  - git remote rm origin
  - git remote add origin https://github.com/suhocki/starlord.git
  - git fetch origin
  - openssl aes-256-cbc -K $encrypted_d9066dcd8080_key -iv $encrypted_d9066dcd8080_iv
    -in keys/secrets.tar.enc -out keys/secrets.tar -d
  - tar xvf keys/secrets.tar -C keys
  - yes | sdkmanager "platforms;android-28"
  - sudo apt-get install jq

before_script:
  - sudo chmod 755 -R scripts
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

script:
  - ./gradlew check test assemble jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/comment_pull_request.sh
  - ./scripts/telegram_notify_on_pull_request.sh

branches:
  only:
    - master
    - develop

before_deploy:
  - git tag $(scripts/versionizer/versionizer.sh name)
  - ./scripts/get_whats_new.sh
  - ./gradlew publish
  - ./scripts/telegram_notify_on_google_play_publish.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $github_api_key
  file_glob: true
  file: app/build/outputs/apk/release/*.apk
  on:
    all_branches: true
