language: android
sudo: required
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - tools

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android/build-cache

before_install:
  - git remote rm origin
  - git remote add origin https://github.com/suhocki/starlord.git
  - git fetch origin
  - openssl aes-256-cbc -K $encrypted_d9066dcd8080_key -iv $encrypted_d9066dcd8080_iv
    -in keys/keystore.jks.enc -out keys/keystore.jks -d
  - openssl aes-256-cbc -K $encrypted_07dbd01e85b3_key -iv $encrypted_07dbd01e85b3_iv
    -in keys/google-play-key.p12.enc -out keys/google-play-key.p12 -d
  - yes | sdkmanager "platforms;android-28"
  # generate release notes for Google Play
  - sudo apt-get install jq
  - cp /dev/null app/src/main/play/release-notes/ru-RU/default.txt
  - curl "https://api.github.com/repos/suhocki/starlord/issues?state=closed&sort=updated-desc" | jq '[.[]|select(has("pull_request") | not)][0]' | jq -r '.title' 2>&1 | tee app/src/main/play/release-notes/ru-RU/default.txt

script:
  - ./gradlew test assembleRelease jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)


branches:
  only:
    - master
    - develop

before_deploy:
  - git tag $(versionizer/versionizer.sh name)
  - ./gradlew publish

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $github_api_key
  file_glob: true
  file: app/build/outputs/apk/release/*.apk
  on:
    all_branches: true
