language: android

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android/build-cache

before_install:
  - git remote rm origin
  - git remote add origin https://github.com/suhocki/starlord.git
  - git fetch origin
  - openssl aes-256-cbc -K $encrypted_d9066dcd8080_key -iv $encrypted_d9066dcd8080_iv
    -in keys/keystore.jks.enc -out keys/keystore.jks -d
  - yes | sdkmanager "platforms;android-28"

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(./build_version.sh)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $github_api_key
  file_glob: true
  file: app/build/outputs/apk/release/*.apk
  on:
    all_branches: true
