language: minimal
os: linux
dist: bionic
sudo: true  # For the 7.5GB limit

env:
  global:
    - EMU_ABI=x86_64
    - EMU_API=28
    - EMU_FLAVOR=default
    - ANDROID_TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
    - ANDROID_HOME="$HOME/android-sdk-linux"
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - PATH="$JAVA_HOME/bin:$HOME/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
    - TERM=dumb
    - GITHUB_BOT_ID=49678291

addons:
  apt:
    packages:
      - jq  # for parsing JSON
      - openjdk-8-jdk-headless  # for building
      - qemu-kvm  # for emulator
      - libvirt-bin  # for emulator
      - ubuntu-vm-builder  # for emulator
      - bridge-utils  # for emulator

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - sudo chmod 755 -R scripts
  - git remote rm origin
  - git remote add origin https://github.com/suhocki/starlord.git
  - git fetch origin
  - openssl aes-256-cbc -K $encrypted_d9066dcd8080_key -iv $encrypted_d9066dcd8080_iv
    -in keys/secrets.tar.enc -out keys/secrets.tar -d
  - tar xvf keys/secrets.tar -C keys

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export AUTHOR_NAME="$(curl -H "Authorization:token ${github_comment_bot_api_key}" -X GET "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}" | jq .user.login | cut -d '"' -f2)"
  # Install Android stuff
  - curl -L $ANDROID_TOOLS_URL -o $HOME/tools.zip
  - unzip -oq $HOME/tools.zip -d $ANDROID_HOME
  - yes | sdkmanager --licenses
  - sdkmanager tools | tr '\r' '\n' | uniq
  - sdkmanager platform-tools | tr '\r' '\n' | uniq
  - ./scripts/start_emulator.sh
  # For the lint checking mechanism
  - mkdir -p $HOME/.cache/lint

script:
  # Split up to reduce memory requirements
  - ./gradlew --stacktrace ktlintCheck
  - ./gradlew --stacktrace detekt
  - ./gradlew --stacktrace assembleDebug
  - ./gradlew --stacktrace assembleRelease
  - ./gradlew --stacktrace testDebug
  - ./gradlew --stacktrace jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/telegram_notify_on_pull_request.sh
  - ./scripts/comment_pull_request_on_success.sh

after_failure:
  - ./scripts/comment_pull_request_on_failure.sh

branches:
  only:
    - master
    - develop

before_deploy:
  - ./gradlew connectedDebugAndroidTest
  - ./scripts/get_whats_new.sh
  - ./gradlew publish
  - ./scripts/telegram_notify_on_google_play_publish.sh
  - git tag $(scripts/versionizer/versionizer.sh name)

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $github_api_key
  file_glob: true
  file: app/build/outputs/apk/release/*.apk
  on:
    all_branches: true
